services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.92 # .91 is Rancher
        aliases:
          - portainer
    ports:
      - "9010:9000" # Web UI over HTTP (9100 is used by Prometheus node-exporter)
      - "9443:9443" # Web UI over HTTPS (self-signed)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
volumes:
  portainer_data:
    name: portainer_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Orchestration/Portainer/data
networks:
  GroupNetwork:
    driver: bridge
    external: true
