version: "3.8"
services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    volumes:
      - Neo4J_data:/data
      - Neo4J_conf:/conf/
    ports:
      - 7474:7474
      - 7687:7687
    networks:
        - neo4j_go_net
    command: neo4j
networks:
  neo4j_go_net:
    driver: bridge
volumes:
  Neo4J_data:
    name: Neo4J_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Neo4J\data
  Neo4J_conf:
    name: Neo4J_conf
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Neo4J\conf\