md $HOME/docker/volumes/ApacheCassandra
md $HOME/docker/volumes/InfluxDb/config
md $HOME/docker/volumes/InfluxDb/db
md $HOME/docker/volumes/MongoDb/data
md $HOME/docker/volumes/MSSQL/data
md $HOME/docker/volumes/MSSQL/log
md $HOME/docker/volumes/MSSQL/secrets
md $HOME/docker/volumes/MySQL
md $HOME/docker/volumes/Neo4J/data
md $HOME/docker/volumes/Neo4J/conf
md $HOME/docker/volumes/PostgreSQL/Data
md $HOME/docker/volumes/PostgreSQL/pgadmin4data
md $HOME/docker/volumes/Redis/cache
md $HOME/docker/volumes/Grafana/storage
md $HOME/docker/volumes/Grafana/storage
md $HOME/docker/volumes/Rancher/data
md $HOME/docker/volumes/RabbitMQ/data
md $HOME/docker/volumes/RabbitMQ/log
md $HOME/docker/volumes/CockroachDB/data