mkdir C:\docker\volumes\ApacheCassandra
mkdir C:\docker\volumes\InfluxDb\config
mkdir C:\docker\volumes\InfluxDb\db
mkdir C:\docker\volumes\MongoDb\data
mkdir C:\docker\volumes\MSSQL\data
mkdir C:\docker\volumes\MSSQL\log
mkdir C:\docker\volumes\MSSQL\secrets
mkdir C:\docker\volumes\MySQL
mkdir C:\docker\volumes\Neo4J\data
mkdir C:\docker\volumes\Neo4J\conf
mkdir C:\docker\volumes\PostgreSQL\Data
mkdir C:\docker\volumes\PostgreSQL\pgadmin4data
mkdir C:\docker\volumes\Redis\cache
mkdir C:\docker\volumes\Grafana\storage
mkdir C:\docker\volumes\Grafana\storage
mkdir C:\docker\volumes\Rancher\data
mkdir C:\docker\volumes\RabbitMQ\data
mkdir C:\docker\volumes\RabbitMQ\log
mkdir C:\docker\volumes\CockroachDB\data
mkdir C:\docker\volumes\Terraform\data
mkdir C:\docker\volumes\Nginx\www
mkdir C:\docker\volumes\Nginx\Nginx
mkdir C:\docker\volumes\Nginx-UI
mkdir C:\docker\volumes\Kafka\Kafka\data\
mkdir C:\docker\volumes\Kafka\Kafka\secrets\
mkdir C:\docker\volumes\Kafka\Zookeeper\data\
mkdir C:\docker\volumes\Kafka\Zookeeper\log\
mkdir C:\docker\volumes\Kafka\Zookeeper\secrets\
mkdir C:\docker\volumes\ElasticSearch\certs
mkdir C:\docker\volumes\ElasticSearch\data01
mkdir C:\docker\volumes\ElasticSearch\data02
mkdir C:\docker\volumes\ElasticSearch\data03
mkdir C:\docker\volumes\ElasticSearch\logs01
mkdir C:\docker\volumes\ElasticSearch\logs02
mkdir C:\docker\volumes\ElasticSearch\logs03
mkdir C:\docker\volumes\ElasticSearch\kibanadatadata03
mkdir C:\docker\volumes\SonarQube\data
mkdir C:\docker\volumes\SonarQube\extensions
mkdir C:\docker\volumes\SonarQube\logs
mkdir C:\docker\volumes\Mediawiki\html
