mkdir C:\docker\volumes\ApacheCassandra
mkdir C:\docker\volumes\InfluxDb\config
mkdir C:\docker\volumes\InfluxDb\db
mkdir C:\docker\volumes\MongoDb\data
mkdir C:\docker\volumes\MSSQL\data
mkdir C:\docker\volumes\MSSQL\log
mkdir C:\docker\volumes\MSSQL\secrets
mkdir C:\docker\volumes\MySQL
mkdir C:\docker\volumes\Neo4J\data
mkdir C:\docker\volumes\Neo4J\conf
mkdir C:\docker\volumes\PostgreSQL\Data
mkdir C:\docker\volumes\PostgreSQL\pgadmin4data
mkdir C:\docker\volumes\Redis\cache
mkdir C:\docker\volumes\Grafana\storage
mkdir C:\docker\volumes\Grafana\storage
mkdir C:\docker\volumes\Rancher\data
mkdir C:\docker\volumes\RabbitMQ\data
mkdir C:\docker\volumes\RabbitMQ\log
mkdir C:\docker\volumes\CockroachDB\data
mkdir C:\docker\volumes\Terraform\data
mkdir C:\docker\volumes\Nginx\www
mkdir C:\docker\volumes\Nginx\Nginx
mkdir C:\docker\volumes\Nginx-UI
mkdir C:\docker\volumes\Kafka\Kafka\data\
mkdir C:\docker\volumes\Kafka\Kafka\secrets\
mkdir C:\docker\volumes\Kafka\Zookeeper\data\
mkdir C:\docker\volumes\Kafka\Zookeeper\log\
mkdir C:\docker\volumes\Kafka\Zookeeper\secrets\