version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: Password123
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.13
        aliases:
          - mongodb
    volumes:
      - MongoDb_Data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "user"
      ME_CONFIG_BASICAUTH_PASSWORD: "Password123"
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_AUTH_USERNAME: "user"
      ME_CONFIG_MONGODB_AUTH_PASSWORD: "Password123"
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: "mongodb"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.24
        aliases:
          - mongoexpress
volumes:
  MongoDb_Data:
    name: MongoDb_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MongoDb\data
networks:
  GroupNetwork:
    driver: bridge
    external: true