version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: Password123
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.13
        aliases:
          - mongodb
    volumes:
      - MongoDb_Data:/data/db
  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://user:Password123@localhost:27017/db?ssl=false
volumes:
  MongoDb_Data:
    name: MongoDb_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\MongoDb\data
networks:
  GroupNetwork:
    driver: bridge
    external: true