
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=svercuski
      - MONGO_INITDB_ROOT_PASSWORD=Password123
    volumes:
      - C:\docker\volumes\MongoDb\data:/data/db
  mongo-express:
    image: mongo-express:latest
    ports:
      - '8081:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://svercuski:Password123@localhost:27017/db?ssl=false