version: "3.8"
services:
  client:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.130
        aliases:
          - nginx
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
  ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.131
        aliases:
          - nginxui
    ports:
      - 8080:80
      - 8443:443
      - 5200-5300:5200-5300
    volumes:
      - nginx:/etc/nginx
      - rabbinginx_ui:/etc/nginx-ui
      - nginix_www:/var/www
volumes:
  rabbinginx_ui:
    name: rabbinginx_ui
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Nginx-UI
  nginx:
    name: nginx
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Nginx\Nginx
  nginix_www:
    name: nginix_www
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Nginx\www
networks:
  GroupNetwork:
    driver: bridge
    external: true