version: "3.8"
services:
  client:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./src:/usr/share/nginx/html
  ui:
    image: uozi/nginx-ui:latest
    container_name: nginx-ui
    ports:
      - 8080:80
      - 8443:443
      - 5200-5300:5200-5300
    volumes:
      - /mnt/user/appdata/nginx:/etc/nginx
      - /mnt/user/appdata/nginx-ui:/etc/nginx-ui
      - /var/www:/var/www
