CREATE ROLE sonarqube WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:fT8wwn21VI3cGwXzmEmbQg==$VWuXzRmcSKK5M1stPq4BsqcBTU9r+TLR5lSvlQDWmrk=:WAepeMOy2ThWFlNE+SWQxDGwgYzPtRCUQMEBrOvgEHY=';

CREATE DATABASE "sonar"
    WITH
    OWNER = sonarqube
    ENCODING = 'UTF8'
    LC_COLLATE = 'en_US.utf8'
    LC_CTYPE = 'en_US.utf8'
    LOCALE_PROVIDER = 'libc'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT CREATE, CONNECT ON DATABASE "sonar" TO sonarqube;
GRANT TEMPORARY ON DATABASE "sonar" TO sonarqube WITH GRANT OPTION;