USE [master]
GO

IF NOT EXISTS (SELECT name FROM sys.server_principals WHERE name = 'sonarqube')
BEGIN
    CREATE LOGIN [sonarqube] WITH PASSWORD = N'Password123', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=ON;
END
GO

/****** Object:  Database [sonar]    Script Date: 11/12/2023 12:41:11 PM ******/
CREATE DATABASE [sonar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'sonar', FILENAME = N'/var/opt/mssql/data/sonar.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'sonar_log', FILENAME = N'/var/opt/mssql/data/sonar_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 COLLATE SQL_Latin1_General_CP1_CS_AS
 WITH LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [sonar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [sonar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [sonar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [sonar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [sonar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [sonar] SET ARITHABORT OFF 
GO

ALTER DATABASE [sonar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [sonar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [sonar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [sonar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [sonar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [sonar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [sonar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [sonar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [sonar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [sonar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [sonar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [sonar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [sonar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [sonar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [sonar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [sonar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [sonar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [sonar] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [sonar] SET  MULTI_USER 
GO

ALTER DATABASE [sonar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [sonar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [sonar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [sonar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [sonar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [sonar] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [sonar] SET QUERY_STORE = ON
GO

ALTER DATABASE [sonar] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [sonar] SET  READ_WRITE 
GO

USE [sonar];
GO

CREATE USER [sonarqube] FOR LOGIN [sonarqube];
GO

EXEC sp_addrolemember N'db_owner', N'sonarqube';
GO