version: "3.8"
services:
  sonarqube:
    image: sonarqube:community
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgresql:5432/sonar
      SONAR_JDBC_USERNAME: user@user.com
      SONAR_JDBC_PASSWORD: Password123
    volumes:
      - sonarqube_data:/opt/SonarQube/data
      - sonarqube_extensions:/opt/SonarQube/extensions
      - sonarqube_logs:/opt/SonarQube/logs
    ports:
      - 9000:9000
    networks:
        GroupNetwork:
          ipv4_address: 192.168.16.170
          aliases:
            - sonarqube
volumes:
  sonarqube_data:
    name: sonarqube_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\SonarQube\data\
  sonarqube_extensions:
    name: sonarqube_extensions
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\SonarQube\extensions\
  sonarqube_logs:
    name: sonarqube_logs
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\SonarQube\logs\
networks:
  GroupNetwork:
    driver: bridge
    external: true
