version: "3.8"
services:
  oracle-db:
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Password123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.25
        aliases:
          - oracle
volumes:
  oracle-data:
    name: oracle-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\Oracle\Data
  oracle-backup:
    name: oracle-data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\Oracle\Backup
networks:
  GroupNetwork:
    driver: bridge
    external: true