services:
  supertokens: # SuperTokens Core
    image: registry.supertokens.io/supertokens/supertokens-postgresql:9.3
    container_name: supertokens
    restart: unless-stopped
    ports:
      - "3567:3567"
    environment:
      # Requires the PostgreSQL stack (Databases/PostgreSQL) with a "supertokens" database created
      POSTGRESQL_CONNECTION_URI: "postgresql://user%40user.com:Password123@postgresql:5432/supertokens"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.211
        aliases:
          - supertokens
networks:
  GroupNetwork:
    driver: bridge
    external: true
