version: "3.8"
services:
  terraform:
    image: hashicorp/terraform:latest
    container_name: terraform
    volumes:
      - .:/infra
    working_dir: /infra
    environment:
      TZ: "America/Eastern"
  gaia:
    image: gaiaapp/gaia:latest
    container_name: gaia
    ports: 
      - "8080:8080"
    environment:
      GAIA_MONGODB_URI: mongodb://mongo/gaia
      GAIA_RUNNER_API_PASSWORD: 123456
      GAIA_EXTERNAL_URL: http://gaia:8080
  runner:
    image: "gaiaapp/runner"
    container_name: runner
    environment:
      GAIA_URL: http://gaia:8080
      GAIA_RUNNER_API_PASSWORD: 123456
    volumes:
      - terraform_data:/var/run/docker.sock
  mongo:
    image: mongo:latest
    container_name: mongo
volumes:
  terraform_data:
    name: terraform_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Terraform\data