version: "3.8"
services:
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass Password123
    volumes: 
      - C:\docker\volumes\Redis\cache:/data
volumes:
  cache:
    driver: local