version: "3.8"
services:
  cache:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --requirepass Password123
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.19
        aliases:
          - redis
    volumes: 
      - redis_cache:/data
volumes:
  redis_cache:
    name: redis_cache
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\Redis\cache
networks:
  GroupNetwork:
    driver: bridge
    external: true