services:
  cache:
    image: redis:${REDIS_VERSION:-latest}
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --save ${REDIS_SAVE:-20 1} --requirepass ${REDIS_PASSWORD:-Password123}
    networks:
      GroupNetwork:
        ipv4_address: ${REDIS_IP:-192.168.16.19}
        aliases:
          - redis
    volumes:
      - redis_cache:/data
volumes:
  redis_cache:
    name: redis_cache
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Redis/cache
networks:
  GroupNetwork:
    driver: bridge
    external: true
