services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    restart: unless-stopped
    ports:
      - 9042:9042
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.10
        aliases:
          - cassandra
    volumes:
      - apache_cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: DockerCluster
volumes:
  apache_cassandra:
    name: apache_cassandra
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Databases/ApacheCassandra
networks:
  GroupNetwork:
    driver: bridge
    external: true
