services:
  cassandra:
    image: cassandra:${CASSANDRA_VERSION:-latest}
    container_name: cassandra
    restart: unless-stopped
    ports:
      - "${CASSANDRA_PORT:-9042}:9042"
    networks:
      GroupNetwork:
        ipv4_address: ${CASSANDRA_IP:-192.168.16.10}
        aliases:
          - cassandra
    volumes:
      - apache_cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: "${CASSANDRA_CLUSTER_NAME:-DockerCluster}"
volumes:
  apache_cassandra:
    name: apache_cassandra
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/ApacheCassandra
networks:
  GroupNetwork:
    driver: bridge
    external: true
