version: "3.8"
services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - 9042:9042
    volumes:
      - apache_cassandra:/var/lib/cassandra
    environment:
      CASSANDRA_CLUSTER_NAME: DockerCluster
volumes:
  apache_cassandra:
    name: apache_cassandra
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\ApacheCassandra