version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - C:\docker\volumes\ApacheCassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=DockerCluster