version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "Password123"
      MYSQL_ROOT_PASSWORD: "Password123"
    ports:
      - "33066:3306"
    expose:
      - "3306"
    volumes:
      - C:\docker\volumes\MySQL:/var/lib/mysql
volumes:
  my-db: