version: "3.8"
services:
  db:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "Password123"
      MYSQL_ROOT_PASSWORD: "Password123"
    ports:
      - "33066:3306"
    expose:
      - "3306"
    volumes:
      - MySQL_Data:/var/lib/mysql
volumes:
  MySQL_Data:
    name: MySQL_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\MySQL