services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.26
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter:latest
    volumes:
      - node_exporter_proc:/host/proc:ro
      - node_exporter_sys:/host/sys:ro
      - node_exporter_root:/rootfs:ro    
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($|/)'
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.27
    ports:
      - 9100:9100
  alertmanager:
    image: prom/alertmanager:latest
    volumes:
      - alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.28
        aliases:
          - prometheus
    ports:
      - 9093:9093
volumes:
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/
  alertmanager:
    name: alertmanager
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/alertmanager
  node_exporter_proc:
    name: node_exporter_proc
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/proc
  node_exporter_sys:
    name: node_exporter_sys
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/sys
  node_exporter_root:
    name: node_exporter_root
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/
  prometheus_data:
    name: prometheus_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/Prometheus/prometheus_data
networks:
  GroupNetwork:
    driver: bridge
    external: true
