services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - $HOME/docker/volumes/Databases/Prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - $HOME/docker/volumes/Databases/Prometheus/rules.yml:/alertmanager/rules.yml"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.26
    ports:
      - 9090:9090
  node-exporter:
    image: prom/node-exporter:latest
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.27
    ports:
      - 9100:9100
  alert-manager:
    image: prom/alertmanager:latest
    volumes:
      - $HOME/docker/volumes/Databases/Prometheus/alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.28
    ports:
      - 9093:9093
volumes:
  prometheus:
    name: prometheus
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Databases/Prometheus/
networks:
  GroupNetwork:
    driver: bridge
    external: true
