version: "3.8"
services:
  cockroachDb:
   image: cockroachdb/cockroach:latest
   ports:
     - 26257:26257
     - 8080:8080
   command:
    start-single-node --insecure
   volumes:
    - C:\docker\volumes\CockroachDB\data:/cockroach/cockroach-data