services:
  pg:
    image: proget.inedo.com/productimages/inedo/proget:24.0.2
    container_name: proget
    restart: unless-stopped
    environment:
      PROGET_SQL_CONNECTION_STRING: "Data Source=192.168.16.14;Initial Catalog=Proget;User ID=Proget;Password=Password123"
      ASPNETCORE_URLS: "http://*:80;https://*:443"
      SSL_CERT_FILE: "proget.cer"
    ports:
      - "8091:80"
      - "8092:443"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.200
        aliases:
          - proget
    volumes:
      - Proget_Data:/var/proget/packages
      - Proget_SSL:/var/proget/ssl
# Update this path to persist your ProGet packages storage
volumes:
  Proget_Data:
    name: Proget_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Packages/ProGet/packages
  Proget_SSL:
    name: Proget_SSL
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Packages/ProGet/ssl
networks:
  GroupNetwork:
    driver: bridge
    external: true
