services:
  pg:
    image: proget.inedo.com/productimages/inedo/proget:${PROGET_VERSION:-24.0.2}
    container_name: proget
    restart: unless-stopped
    environment:
      PROGET_SQL_CONNECTION_STRING: "${PROGET_SQL_CONNECTION_STRING:-Data Source=mssqldb;Initial Catalog=Proget;User ID=Proget;Password=Password123;TrustServerCertificate=True}"
      ASPNETCORE_URLS: "${PROGET_ASPNETCORE_URLS:-http://*:80;https://*:443}"
      SSL_CERT_FILE: "${PROGET_SSL_CERT_FILE:-proget.cer}"
    ports:
      - "${PROGET_HTTP_PORT:-8091}:80"
      - "${PROGET_HTTPS_PORT:-8092}:443"
    networks:
      GroupNetwork:
        ipv4_address: ${PROGET_IP:-192.168.16.200}
        aliases:
          - proget
    volumes:
      - Proget_Data:/var/proget/packages
      - Proget_SSL:/var/proget/ssl
volumes:
  Proget_Data:
    name: Proget_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Packages/ProGet/packages
  Proget_SSL:
    name: Proget_SSL
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Packages/ProGet/ssl
networks:
  GroupNetwork:
    driver: bridge
    external: true
