version: "3.8"
services:
  backstage:
    image: backstage
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.30
        aliases:
          - backstage
    environment:
      # This value must match the name of the postgres configuration block.
      POSTGRES_HOST: postgresql
      POSTGRES_USER: user@user.com
      POSTGRES_PASSWORD: Password123
      # NODE_OPTIONS: --no-node-snapshot # uncomment for NODE 20+
    ports:
      - 7007:7007
networks:
  GroupNetwork:
    driver: bridge
    external: true