services:
  postgres:
    image: postgres:latest
    container_name: posgresql
    restart: unless-stopped
    environment:
      POSTGRES_USER: user@user.com
      POSTGRES_PASSWORD: Password123
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.17
        aliases:
          - postgresql
    logging:
      options:
        max-size: 10m
        max-file: 3
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/data
      # copy the sql script to create tables
      # - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
  pgadmin4:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: user@user.com
      PGADMIN_DEFAULT_PASSWORD: Password123
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.18
        aliases:
          - pgadmin4
    ports:
      - 5050:80
    volumes:
      - pgadmin4_data:/var/lib/pgadmin
volumes:
  postgresql_data:
    name: postgresql_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Databases/PostgreSQL/Data
  pgadmin4_data:
    name: pgadmin4_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Databases/PostgreSQL/pgadmin4data
networks:
  GroupNetwork:
    driver: bridge
    external: true
