services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: user
      DOCKER_INFLUXDB_INIT_PASSWORD: Password123
      DOCKER_INFLUXDB_INIT_ORG: TheSoftwareDispensary
      DOCKER_INFLUXDB_INIT_BUCKET: TSD
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.12
        aliases:
          - influxdb
    volumes:
      - InfluxDB_Config:/etc/influxdb2
      - InfluxDB_Data:/var/lib/influxdb2
volumes:
  InfluxDB_Config:
    name: InfluxDB_Config
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/InfluxDb/config/
  InfluxDB_Data:
    name: InfluxDB_Data
    driver: local
    driver_opts:
      type: none
      o: bind
networks:
  GroupNetwork:
    driver: bridge
    external: true
