version: "3.8"
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: sql-server
    restart: unless-stopped
    environment:
      MSSQL_SA_PASSWORD: Password123
      ACCEPT_EULA: Y
      MSSQL_AGENT_ENABLED: 1
    ports:
      - 1433:1433
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.14
        aliases:
          - mssqldb
    volumes:
      - MSSQL_Data:/var/opt/mssql/data
      - MSSQL_Log:/var/opt/mssql/log
      - MSSQL_Secrets:/var/opt/mssql/secrets
volumes:
  MSSQL_Data:
    name: MSSQL_Data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MSSQL\data
  MSSQL_Log:
    name: MSSQL_Log
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MSSQL\log
  MSSQL_Secrets:
    name: MSSQL_Secrets
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MSSQL\secrets
networks:
  GroupNetwork:
    driver: bridge
    external: true