services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.72
        aliases:
          - rabbitmq
volumes:
  rabbitmq_data:
    name: rabbitmq_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Messaging/RabbitMQ/data/
  rabbitmq_log:
    name: rabbitmq_log
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/docker/volumes/Messaging/RabbitMQ/log/
networks:
  GroupNetwork:
    driver: bridge
    external: true
