version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_log:/var/log/rabbitmq
    networks:
        - rabbitmq_go_net
volumes:
  rabbitmq_data:
    name: rabbitmq_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\RabbitMQ\data\
  rabbitmq_log:
    name: rabbitmq_log
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\RabbitMQ\log\
networks:
  rabbitmq_go_net:
    driver: bridge