version: "3.8"
services:
  mysql:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: "Password123"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "Password123"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.22
        aliases:
          - mysqldb
    volumes:
      - MariaDB_backup:/backup
      - MariaDB_data:/var/lib/mysql:Z
  adminer:
    image: adminer
    restart: always
    ports:
      - 8087:8080
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.23
        aliases:
          - mysqldb
volumes:
  MariaDB_backup:
    name: MariaDB_backup
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MariaDB\Backup
  MariaDB_data:
    name: MariaDB_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Databases\MariaDB\Data
networks:
  GroupNetwork:
    driver: bridge
    external: true