services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: "Password123"
      MARIADB_USER: "user"
      MARIADB_PASSWORD: "Password123"
    ports:
      - 3307:3306 # 3306 is used by MySQL
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.22
        aliases:
          - mariadb
    volumes:
      - MariaDB_backup:/backup
      - MariaDB_data:/var/lib/mysql:Z
  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8087:8080
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.23
        aliases:
          - adminer
volumes:
  MariaDB_backup:
    name: MariaDB_backup
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/MariaDB/Backup
  MariaDB_data:
    name: MariaDB_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Databases/MariaDB/Data
networks:
  GroupNetwork:
    driver: bridge
    external: true
