version: '3.8'

services:
  registry:
    image: registry:latest
    ports:
    - 5000:5000
    environment:
      REGISTRY_HTTP_HEADERS_Access-Control-Origin: '[http://localhost]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: '[HEAD,GET,OPTIONS,DELETE]'
      REGISTRY_HTTP_HEADERS_Access-Control-Credentials: '[true]'
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: '[Authorization,Accept,Cache-Control]'
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: '[Docker-Content-Digest]'
      REGISTRY_STORAGE_DELETE_ENABLED: 'true'
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    container_name: registry-server
    volumes:
      - registry_data:/data
    networks:
        GroupNetwork:
          ipv4_address: 192.168.16.180
          aliases:
            - dockerregistry
  registry-ui:
    image: joxit/docker-registry-ui:latest
    ports:
      - 5001:80
    environment:
      - SINGLE_REGISTRY=true
      - REGISTRY_TITLE=Docker Registry UI
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - NGINX_PROXY_PASS_URL=http://localhost:5000
      - SHOW_CATALOG_NB_TAGS=true
      - CATALOG_MIN_BRANCHES=1
      - CATALOG_MAX_BRANCHES=1
      - TAGLIST_PAGE_SIZE=100
      - REGISTRY_SECURED=false
      - CATALOG_ELEMENTS_LIMIT=1000
    container_name: registry-ui
volumes:
  registry_data:
    name: registry_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: C:\docker\volumes\Registry\data\
networks:
  GroupNetwork:
    driver: bridge
    external: true
