services:
  apache:
    image: httpd:${APACHE_VERSION:-latest}
    container_name: apache
    restart: unless-stopped
    networks:
      GroupNetwork:
        ipv4_address: ${APACHE_IP:-192.168.16.132}
        aliases:
          - apache
    ports:
      - "${APACHE_PORT:-8083}:80"
    volumes:
      - apache_websites:/usr/local/apache2/htdocs
volumes:
  apache_websites:
    name: apache_websites
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/WebServers/Apache
networks:
  GroupNetwork:
    driver: bridge
    external: true
