services:
  mediawiki:
    image: mediawiki:latest
    container_name: mediawiki
    restart: unless-stopped
    ports:
      - 8081:80
    volumes:
      - mediawiki_data:/var/www/html/
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.31
        aliases:
          - mediawiki
volumes:
  mediawiki_data:
    name: mediawiki_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Documentation/Mediawiki/html/
networks:
  GroupNetwork:
    driver: bridge
    external: true
