services:
  rancher:
    image: rancher/rancher:${RANCHER_VERSION:-latest}
    container_name: rancher
    restart: unless-stopped
    ports:
      # 80/443 belong to Nginx Proxy Manager
      - "${RANCHER_HTTP_PORT:-8480}:80/tcp"
      - "${RANCHER_HTTPS_PORT:-8444}:443/tcp"
    networks:
      GroupNetwork:
        ipv4_address: ${RANCHER_IP:-192.168.16.91}
        aliases:
          - rancher
    volumes:
      - rancher_data:/var/lib/rancher
    privileged: true
volumes:
  rancher_data:
    name: rancher_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Orchestration/Rancher/data
networks:
  GroupNetwork:
    driver: bridge
    external: true
