services:
  rancher:
    image: rancher/rancher:latest
    container_name: rancher
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    networks:
      GroupNetwork:
        ipv4_address: 192.168.16.91
        aliases:
          - rancher
    volumes:
      - rancher_data:/var/lib/rancher
    privileged: true
volumes:
  rancher_data:
    name: rancher_data
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${ROOT_VOLUME_DIR:?error}/docker/volumes/Orchestration/Rancher/data
networks:
  GroupNetwork:
    driver: bridge
    external: true
